package ENUM;

public enum ListaPgPuntiFerita {
	PUNTI_FERITA_TOTALI,
	STATO_PG,
	FERITE_ATTUALI,
	FERITE,
	DANNI_NON_LETALI_ATTUALI,
	DANNI_NON_LETALI,
	RIDUZIONE_DEL_DANNO,
	RESISTENZE1,
	RESISTENZE2,
	RESISTENZE3,
	RESISTENZE4,
	RESISTENZE5,
}
