package ENUM;

public enum ListaPgTiriSalvezza {
	TEMPRA_TOTALE,
	TEMPRA_BASE,
	TEMPRA_ABILITA,
	TEMPRA_MAGIA,
	TEMPRA_ALTRO,
	RIFLESSI_TOTALE,
	RIFLESSI_BASE,
	RIFLESSI_ABILITA,
	RIFLESSI_MAGIA,
	RIFLESSI_ALTRO,
	VOLONTA_TOTALE,
	VOLONTA_BASE,
	VOLONTA_ABILITA,
	VOLONTA_MAGIA,
	VOLONTA_ALTRO,
	RESISTENZA_INCANTESIMI,
	NOTE
}
