package ENUM;

public enum ListaPgClasseArmatura {
	TOTALE,
	BONUS_ARMATURA,
	BONUS_SCUDO,
	BONUS_DESTREZZA,
	BONUS_TAGLIA,
	BONUS_NATURALE,
	BONUS_DEVIAZIONE,
	BONUS_ALTRO,
	BONUS_TEMP,
	ARMATURA_SCUDO1,
	ARMATURA_SCUDO_STATISTICA1,
	ARMATURA_SCUDO_BONUS1,
	ARMATURA_SCUDO2,
	ARMATURA_SCUDO_STATISTICA2,
	ARMATURA_SCUDO_BONUS2,
	ARMATURA_SCUDO3,
	ARMATURA_SCUDO_STATISTICA3,
	ARMATURA_SCUDO_BONUS3,
	COLTO_ALLA_SPROVVISTA,
	ATTACCHI_A_CONTATTO,
	FALLIMENTO_INCANTESIMI_ARCANI,
	FLAG_FALLIMENTO_INCANTESIMI_ARCANI,
	PENALITA_PROVA_ARMATURA,
	FLAG_PENALITA_PROVA_ARMATURA,
	BONUS_MASSIMO_DESTREZZA
}
